### ISSUE TITLE
What version of Laravel does this support?

### ISSUE THREAD

**Issue by hotsaucejake** [AidynMakhataev/laravel-surveyjs#3]
I'm using 5.4 on one of my projects.

When I publish the files

```
php artisan vendor:publish --provider="AidynMakhataev\LaravelSurveyJs\LaravelSurveyJsServiceProvider"
```

It doesn't actually publish anything.  If I add the provider to `config/app.php` and try to publish, I get

```
[InvalidArgumentException]        
  Attribute [view] does not exist.
```

I imagine this supports Laravel 5.5+

**Comment by khyoz** [comment]
I have no problem with 5.6

**Comment by hotsaucejake** [comment]
@khyoz read my last line ;)

**Comment by khyoz** [comment]
what don't you understand in mine ? You imagine, and I reported facts ! I didn't check with 5.5 ....
so I don't know if your imagination is correct ;o) 
(take it at 2nd degree, ! nice to see othe people interested by the project)
