### ISSUE TITLE
Axios.put error 405 not allowed.

### ISSUE THREAD

**Issue by sproutlegal** [AidynMakhataev/laravel-surveyjs#4]
On the route /api/survey/{id} I am getting a 405 method not allowed for PUT method. This occurs when i press "save survey" button in the editor for an existing survey.

I have tried changing survey-manager.js to use a different method of updating rather than axios.put, however, to now avail.

I have tried putting in the routes individually, instead of Route::resource, but still not luck. I have looked at route:list in laravel and the routes look fine.

Any ideas?

**Comment by AidynMakhataev** [comment]
Сan you please show result of route:list сommand? And also, which Laravel version do you use?

**Comment by AidynMakhataev** [comment]
I’m closing this issue because it has been inactive. This probably means that it is not reproducible or it has been fixed in a newer version. Please reopen if you still encounter this issue.
Thank you!

**Comment by DCdeBrabander** [comment]
Damn it, I have the exact same issue. I am running Laravel 5.8 and I'm getting apache 404/405's on routes I defined(! If I go to an undefined route I get a Laravel 404..?).
 
@sproutlegal what did you do to fix it?
