### ISSUE TITLE
Is there a way to add widgets via the survey-manager.php config file?

### ISSUE THREAD

**Issue by sproutlegal** [AidynMakhataev/laravel-surveyjs#5]

**Comment by illyaBendik** [comment]
I have the same problem. Can yo help me please ?

**Comment by yavgel85** [comment]
It's wery intresting question for me too )) I'll try to add Signature Pad (like this   https://surveyjs.io/Examples/Library?id=custom-widget-signaturepad&platform=Vue&theme=default)

**Comment by AidynMakhataev** [comment]
Released version 0.3.1 with custom widget support and some refactoring in code base.  All available widgets is listed in config file. You need to: 

1. `composer update`
2. `php artisan vendor:publish --provider="AidynMakhataev\LaravelSurveyJs\LaravelSurveyJsServiceProvider" --force`
3. Enable necessary widgets in `survey-manager.php`, by default they are disabled.

**Comment by yavgel85** [comment]
Thank you so mush !!!!  )))

пт, 21 дек. 2018 г. в 09:58, Aidyn Makhataev <notifications@github.com>:
